name: CI_UBUNTU_18_04_RELEASE

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_FOLDER: ${{github.workspace}}/build
  DEVEL_FOLDER: ${{github.workspace}}/devel

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
      #
      # Checkout the current package locally
      #
      - uses: actions/checkout@v2

      #
      # Setup the machines and build environment
      #
      - uses: machines-in-motion/mim_github_actions/setup_ubuntu18_04@master
      - uses: machines-in-motion/mim_github_actions/treep_clone@master
        - with:
          treep_configurations: >
            "git@github.com:machines-in-motion/treep_machines_in_motion.git"
          projects_or_repos: "PACKAGE_TEMPLATE_DEPENDENCIES"
      
      #
      # Build the source dependencies
      #
      - name: Build the dependencies.
        working-directory: ${{github.workspace}}/devel/workspace
        shell: bash
        run: >
          colcon build --cmake-args
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DPYBIND11_TEST=OFF
          -DBUILD_TESTING=OFF

      #
      # Build and test the current package.
      #

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: >
          source ${{github.workspace}}/devel/workspace/install/setup.bash &&
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: >
          source ${{github.workspace}}/devel/workspace/install/setup.bash &&
          cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: >
          source ${{github.workspace}}/devel/workspace/install/setup.bash &&
          env CTEST_OUTPUT_ON_FAILURE=1 ctest -C $BUILD_TYPE
