name: CI_UBUNTU_18_04_RELEASE

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_FOLDER: ${{github.workspace}}/build
  DEVEL_FOLDER: ${{github.workspace}}/devel

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
      #
      # Setup the machines and build environment
      #
      - name: Setup Ubuntu18.04.
        uses: machines-in-motion/mim_github_actions/setup_ubuntu18_04@main

      #
      # Checkout the current package locally
      #
      - name: Checkout current repo.
        uses: actions/checkout@v2

      #
      # Activate the secret ssh key
      #
      - name: Spawn ssh-agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GA_SSH_PRIVATE_KEY }}

      #
      # Clone the dependencies that needs to be built.
      #
      - name: Clone dependencies and build them.
        uses: machines-in-motion/mim_github_actions/treep_clone_and_build@main
        with:
          treep_configurations: >
            "git@github.com:machines-in-motion/treep_machines_in_motion.git"
          projects_or_repos: "PACKAGE_TEMPLATE_DEPENDENCIES"

      #
      # Build and test the current package.
      #
      - name: Clone dependencies and build them.
        uses: machines-in-motion/mim_github_actions/cmake_build_and_ctest@main
